backend:
  name: git-gateway
  branch: master

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    extension: "html"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/post.html",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Post Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
  - name: "PostList"
    label: "Posts"
    files:
      - label: "posts"
        name: "posts"
        file: "src/posts/posts.json"
        fields:
          - label: "Post List"
            name: "posts"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Featured Image", name: "featuredImage", widget: "image" }
     
