backend:
  name: git-gateway
  branch: master

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    - file: "src/posts/posts.json"
      label: "Posts"
      name: "posts"
      widget: "list"
      fields:
        - {
            label: "Layout",
            name: "layout",
            widget: "hidden",
            default: "layouts/post.html",
          }
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Featured Image", name: "featuredImage", widget: "image" }
