backend:
  name: git-gateway
  branch: master

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    - file: "src/posts/posts.json"
      label: "Posts"
      name: "posts"
      widget: "list"
      fields:
        - {
            label: FAQS
            name: faqs
            widget: list
            fields: 
              - label: FAQ
                name: faq
                widget: object
                fields:
                  - { label: Question, name: question, widget: string, default: "Question" }
                  - { label: Answer, name: answer, widget: string, default: "Answer" }
          } 
